# Generated by Django 5.1 on 2024-09-02 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0003_status_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lms_app.status",
            ),
        ),
    ]
