# Generated by Django 5.1 on 2024-09-02 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0004_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime(2024, 9, 2, 20, 37, 50, 532490)
            ),
        ),
    ]
