# Generated by Django 5.1 on 2024-09-05 13:55

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0005_alter_book_publication_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="borrower",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime(2024, 9, 5, 14, 55, 13, 11887)
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name=django.contrib.auth.models.User
                    ),
                ),
                ("profile_image", models.URLField(blank=True, null=True)),
                (
                    "profile_bio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "books_borrowed",
                    models.ManyToManyField(blank=True, to="lms_app.book"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
