# Generated by Django 5.1 on 2024-09-06 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0007_profile_book_count_alter_book_publication_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime(2024, 9, 6, 20, 18, 3, 792478)
            ),
        ),
    ]
